// ClientAngular/src/app/home/bill-of-exchange/bill-of-exchange-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiClientService } from '@app/home/api-client.service';
import { BillOfExchangeWithCurrentOwner } from '@app/home/models/bill-of-exchange-with-current.owner';
import { take } from 'rxjs/operators';
import { Endorsement } from '../models/endorsement';

@Component({
  selector: 'app-bill-of-exchange',
  templateUrl: './bill-of-exchange-detail.component.html',
  styleUrls: ['./bill-of-exchange-detail.component.scss'],
})
export class BillOfExchangeDetailComponent implements OnInit {
  id: number;
  billOfExchangeWithCurrentOwner: BillOfExchangeWithCurrentOwner;
  endorsementsColumns = ['id', 'billId', 'previousEndorsementId', 'newBeneficiary'];
  endorsements: Endorsement[] = [];
  isLoading = true;

  constructor(
    private apiClientService: ApiClientService,
    private activatedRoute: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.activatedRoute.queryParams.pipe(take(1)).subscribe((params) => {
      if (params.id) {
        this.id = params.id;

        this.apiClientService.getBillOfExchangeWithCurrentOwner(this.id).subscribe((result) => {
          if (result) {
            this.billOfExchangeWithCurrentOwner = result;
          }
        });

        this.apiClientService.getEndorsementsForBill(this.id).subscribe((result) => {
          if (result) {
            this.endorsements = result;
          }
        });
      }
    });
  }

  openPartyDetail(beneficiaryId: number) {
    this.router.navigate(['party'], { queryParams: { id: beneficiaryId } });
  }
}

<mat-card>
  <mat-card-content>
    <mat-card-title translate>Bill of exchange detail</mat-card-title>
    <div>
      <h4>Bill detail with current owner</h4>
      <div style="width: max-content; display: flex; flex-direction: column" *ngIf="billOfExchangeWithCurrentOwner">
        <span>ID: {{ billOfExchangeWithCurrentOwner.id }}</span>
        <span style="cursor: pointer" (click)="openPartyDetail(billOfExchangeWithCurrentOwner.drawerId)"
          >DrawerId: {{ billOfExchangeWithCurrentOwner.drawerId }}</span
        >
        <span style="cursor: pointer" (click)="openPartyDetail(billOfExchangeWithCurrentOwner.beneficiaryId)"
          >BeneficiaryId: {{ billOfExchangeWithCurrentOwner.beneficiaryId }}</span
        >
        <span>Amount: {{ billOfExchangeWithCurrentOwner.amount }}</span>
        <span style="cursor: pointer" (click)="openPartyDetail(billOfExchangeWithCurrentOwner.ownerId)"
          >OwnerName: {{ billOfExchangeWithCurrentOwner.ownerName }}</span
        >
      </div>
    </div>
    <div style="width: max-content">
      <h4>Endorsements for bill</h4>
      <table style="width: 600px" mat-table [dataSource]="endorsements">
        <ng-container matColumnDef="id">
          <th mat-header-cell *matHeaderCellDef>Id</th>
          <td mat-cell *matCellDef="let row">{{ row.id }}</td>
        </ng-container>

        <ng-container matColumnDef="billId">
          <th mat-header-cell *matHeaderCellDef>Bill ID</th>
          <td mat-cell *matCellDef="let row">{{ row.billId }}</td>
        </ng-container>
        <ng-container matColumnDef="previousEndorsementId">
          <th mat-header-cell *matHeaderCellDef>Previous Endorsement Id</th>
          <td mat-cell *matCellDef="let row">{{ row.previousEndorsementId }}</td>
        </ng-container>
        <ng-container matColumnDef="newBeneficiary">
          <th mat-header-cell *matHeaderCellDef>New Beneficiary</th>
          <td mat-cell style="cursor: pointer" (click)="openPartyDetail(row.newBeneficiaryId)" *matCellDef="let row">
            {{ row.newBeneficiary }}
          </td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="endorsementsColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: endorsementsColumns"></tr>
      </table>
    </div>
  </mat-card-content>
</mat-card>

// Client/src/components/BillOfExchangeDetail/BillOfExchangeDetail.tsx
import { Box, makeStyles } from "@material-ui/core";
import {
  DataGrid,
  GridColDef,
  GridRowParams,
  GridRowsProp,
} from "@material-ui/data-grid";
import React, { useEffect } from "react";
import { useHistory, useParams } from "react-router-dom";
import { http } from "../../api/api";
import { BillOfExchangeWithCurrentOwner, Endorsement } from "../../models";
import Error from "../Error/Error";
import { Wrapper } from "../index";

const endorsementsColumns: GridColDef[] = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "billId", headerName: "Bill ID", width: 200 },
  {
    field: "previousEndorsementId",
    headerName: "Previous endorsement ID",
    width: 250,
  },
  { field: "newBeneficiary", headerName: "New beneficiary", width: 200 },
];

const useStyles = makeStyles({
  root: {
    cursor: "pointer",
    color: "blue",
  },
});

const BillOfExchangeDetail: React.FC = () => {
  const classes = useStyles();
  const history = useHistory();
  let { billId }: any = useParams();
  const [
    billEndorsements,
    setBillEndorsementsRows,
  ] = React.useState<GridRowsProp>([]);
  const [
    ownedBill,
    setOwnedBill,
  ] = React.useState<BillOfExchangeWithCurrentOwner>();

  useEffect(() => {
    http.get("Endorsements", { params: { BillId: billId } }).then(
      (response) => {
        if (response && response.data) {
          const result = response.data as Endorsement[];
          if (result) {
            setBillEndorsementsRows(result);
          }
        }
      },
      (x) => console.log(x)
    );
  }, [billId]);

  useEffect(() => {
    http.get(`BillsOfExchange/${billId}`).then((response) => {
      if (response && response.data) {
        const result = response.data as BillOfExchangeWithCurrentOwner;
        if (result) {
          setOwnedBill(result);
        }
      }
    });
  }, [billId]);

  function goToDetail(param: GridRowParams) {
    goToPartyDetail(param.row.newBeneficiaryId);
  }

  function goToPartyDetail(id: number | undefined) {
    if (id) {
      history.push(`/party/${id}`);
    }
  }

  return (
    <Wrapper>
      <h2 className="o-shell">Bill of Exchange detail</h2>
      <Box
        p={1}
        display="flex"
        flexDirection="column"
        data-testid="BillOfExchangeDetail"
      >
        <h3>Bill detail with current owner</h3>
        {ownedBill ? (
          <Box p={1} display="flex" flexDirection="column">
            ID: {ownedBill.id}
            <span>
              {" "}
              Drawer ID:{" "}
              <span
                className={classes.root}
                onClick={() => goToPartyDetail(ownedBill.drawerId)}
              >
                {ownedBill.drawerId}
              </span>
            </span>
            <span>
              {" "}
              Beneficiary ID:{" "}
              <span
                className={classes.root}
                onClick={() => goToPartyDetail(ownedBill.beneficiaryId)}
              >
                {ownedBill.beneficiaryId}
              </span>
            </span>
            <span>
              {" "}
              Owner Name:{" "}
              <span
                className={classes.root}
                onClick={() => goToPartyDetail(ownedBill.ownerId)}
              >
                {ownedBill.ownerName}
              </span>
            </span>
          </Box>
        ) : (
          <Error error="ERROR: Data for this bill are either invalid or missing" />
        )}
        <Box p={1} style={{ height: 400, width: "100%" }}>
          <h3>Endorsements for bill</h3>
          <DataGrid
            rows={billEndorsements}
            columns={endorsementsColumns}
            onRowClick={goToDetail}
          />
        </Box>
      </Box>
    </Wrapper>
  );
};

export default BillOfExchangeDetail;
